### ISSUE TITLE
"no debug text" + "less payload"?

### ISSUE THREAD

**Issue by n4ru** [ihaveamac/ninjhax2.5-less_services_test#1]
As title states, I would absolutely kill for an improved bootrate ninjhax payload release WITH your no debug text edit. Working on compiling one myself but setting up the environment in windows is killing me.

(I apologize in advance that this isn't actually an issue - keep up the great work!)

**Comment by ihaveamac** [comment]
in my experience boot rate has not increased. has it for you?

**Comment by n4ru** [comment]
Well shit, that was a quick reply. I've only just started setting up my environment to begin modifying and compiling for 3DS so I haven't been able to test much. I assumed that the services you're removing were added between the release of menuhax installer 1.2 and 2.3. There's been significant evidence showing that earlier commits around the time of menuhax' 1.2 release boot SIGNIFICANTLY better than the latest payloads on 9.0 - 9.2. I was skeptical but it's unmistakable after trying it out myself.

**Comment by n4ru** [comment]
References:

At time of 1.2 release, the latest payload commit was this one:
https://github.com/smealum/ninjhax2.x/commit/adea1b7639830691b56b6db9c3b36a50288b12bf

According to GBATemp users and anecdotal testing, this method works to improve bootrates. I am not the best low-level programmer, but I can only assume (and after some light skimming) that many features/services were added to the latest version of the payload that might cause the discrepancy.

https://gbatemp.net/threads/guide-how-to-improve-menuhax-boot-rate-to-nearly-100.410764/

**Comment by ihaveamac** [comment]
ninjhax 2.1 has a much, much better boot rate than 2.5, this is not just a menuhax thing. I actually got 2.1 to build and work with Cubic Ninja but I can't figure out how to build ropbins for it.

you can check out e1d9ee66eb192c2c58db39d86805fc00a3266b5d for the services I removed. it narrows it down to four that *hax and CFW-launching/etc tools need.

by the way, I'm not a low-level programmer at all, I just know how to hide things + read/modify existing code mostly.

**Comment by n4ru** [comment]
Gonna put my foot in my mouth for a second and test your release vs the 1.2 ones (which is actually 2.x ninjhax, probably 2.1) that have proven to work. Will report back in 15.

**Comment by n4ru** [comment]
Okay, interesting results. I'm on o3DS 9.2.

Out of 20 trials:
I got a Yellow Screen twice, white screen once (I've NEVER gotten it frozen here before), and it booted 17 times.

HOWEVER, the statistically significant factor here is that if it passed the flashing debug screens, _it booted every single time_. This was absolutely NOT the case with the normal payload, where it would fail a significant portion of the time (~30% if not more).

(now about that no debug text? ;D )

**Comment by ihaveamac** [comment]
this white screen issue is bizarre. it only happens with menuhax, and I've never encountered it on my two/three Old3DS systems.

"if it passed the flashing debug screens" are you saying it sometimes failed even when it got past the debug screen? I've never seen this happen ever.

**Comment by n4ru** [comment]
I run CtrBootManager with autoboot 0 delay right into rxTools. It fail(ed) often for me after the debug screens.

The splash image from rxTools never showed and it froze on black screen. Your version has at least anecdotally fixed it from what I've seen so far. I had success setting the timeout to 8 seconds (guessing it would flush some services automatically during this time?), but it was still worse than the old payloads which worked nearly all the time with autoboot 0 delay.

**Comment by ihaveamac** [comment]
"(now about that no debug text? ;D )" I suppose if you want it _that_ badly then I'll do some changes later to hide the debugging info.

**Comment by n4ru** [comment]
By the way; Here's a comparison of the changes between 2.1 and 2.5. You can see a list of the services that were changed. Perhaps those are the ones that unnecessarily "bloat" the payload when booting CFW and cause it to fail?

https://github.com/smealum/ninjhax2.x/compare/smealum:f9f1fad0169bef7380e4dd6b30cd596309839ca3...smealum:8b249c1

**Comment by n4ru** [comment]
Specifically:

https://github.com/smealum/ninjhax2.x/compare/smealum:f9f1fad0169bef7380e4dd6b30cd596309839ca3...smealum:8b249c1#diff-da459bc618d7a1826a0a21cf43579b59L390

_Edit: And it looks like those are the ones you actually removed. So maybe you were really on to something._

Why keep hb:mem0 and hb:ndsp?

**Comment by n4ru** [comment]
Finally got it to compile, and I can successfully launch CTRBootManager into rxTools using a version with just ns:s and fs:user.

**Comment by ihaveamac** [comment]
https://gbatemp.net/threads/release-lesshax-cfw-optimized-9-2-payload.415077/
